test_day3/urls.py
# from django.contrib import admin
from django.urls import path
from app01.views import depart,user,pretty,admin,account,task,order,chart,upload,city
from django.urls import path,re_path
from django.views.static import serve
from django.conf import settings


urlpatterns = [
    # path('admin/', admin.site.urls),

    re_path(r'^media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT},name='media'),

    #部门管理
    path('depart/list/', depart.depart_list),
    path('depart/add/', depart.depart_add),
    path('depart/delete/', depart.depart_delete),
    path('depart/<int:ider>/edit/', depart.depart_edit),
    path('depart/multi/', depart.depart_multi),



    #用户管理
    path('user/list/', user.user_list),
    path('user/add/', user.user_add),
    path('user/model/form/add/', user.user_model_form_add),
    path('user/<int:nid>/edit/', user.user_edit),
    path('user/<int:nid>/delete/', user.user_delete),


    #靓号管理
    path('pretty/list/', pretty.pretty_list),
    path('pretty/add/', pretty.pretty_add),
    path('pretty/<int:nid>/edit/', pretty.pretty_edit),
    path('pretty/<int:nid>/delete/', pretty.pretty_delete),


    #管理员账号管理
    path('admin/list/', admin.admin_list),
    path('admin/add/', admin.admin_add),
    path('admin/<int:nid>/edit/', admin.admin_edit),
    path('admin/<int:nid>/delete/', admin.admin_delete),
    path('admin/<int:nid>/reset/', admin.admin_reset),


    #账号登录
    path('login/', account.login),
    path('logout/', account.logout),
    path('image/code/', account.image_code),

    #ajax请求 任务管理
    path('task/list/', task.task_list),
    path('task/ajax/', task.task_ajax),
    path('task/add/', task.task_add),

    #订单管理
    path('order/list/', order.order_list),
    path('order/add/', order.order_add),
    path('order/delete/', order.order_delete),
    path('order/detail/', order.order_detail),
    path('order/edit/', order.order_edit),


    # echarts图表展示
    path('chart/list/', chart.chart_list),
    path('chart/line/', chart.chart_line),
    path('chart/bar/', chart.chart_bar),
    path('chart/pie/', chart.chart_pie),


    # 提交文件
    path('upload/list/', upload.upload_list),
    path('upload/form/', upload.upload_form),
    path('upload/model/form/', upload.upload_model_form),

    #城市列表
    path('city/list/', city.city_list),
    path('city/add/', city.city_add),


    

]

app01/models.py
from django.db import models

# Create your models here.


class Admin(models.Model):

    username = models.CharField(verbose_name="用户名" ,max_length=32)
    password = models.CharField(verbose_name="密码",max_length=64) 

    def  __str__(self) -> str:
        return self.username


class Department(models.Model):
    ''' 部门表 '''
    title = models.CharField(verbose_name="部门",max_length=32)

    def __str__(self) -> str:
        return self.title



class UserInfo(models.Model):
    ''' 员工表 '''
    name = models.CharField(verbose_name= "姓名",max_length=16)
    password = models.CharField(verbose_name= "密码",max_length=64)
    position = models.CharField(verbose_name= "职位",max_length=32)
    age = models.IntegerField(verbose_name="年龄")
    # max_digits：数字允许的最大位数   decimal_places：小数的最大位数
    account = models.DecimalField(verbose_name="账户金额",max_digits=10,decimal_places=2 , default=0)
    # 在mysql里面有个datetime类型，在Django的ORM语言里面对应的类是DateTimieField。    
    # create_time = models.DateTimeField(verbose_name="入职时间")
    create_time = models.DateField(verbose_name="入职时间")


    #超级连接删除
    depart = models.ForeignKey(to="Department",verbose_name= "部门" ,to_field="id",on_delete=models.CASCADE)

    # 在django中的约束
    gender_choices = (
        (1,"男"),
        (2,"女"),
    )

    gender = models.SmallIntegerField(verbose_name="性别",choices=gender_choices)



class PrettyNum(models.Model):
    ''' 靓号表 '''
    
    number = models.CharField(verbose_name="手机号" , max_length=32)

    #默认情况可以为空 添加 ：null=True,blank=True
    price = models.IntegerField(verbose_name="价格",default=0) 

    level_choices = (
        (1,"1级"),
        (2,"2级"),
        (3,"3级"),
        (4,"4级"),
    )
    level = models.SmallIntegerField(verbose_name="级别" , choices=level_choices , default=1)

    status_choices = (
        (1,"未购买"),
        (2,"已购买"),
    )

    status = models.SmallIntegerField(verbose_name="状态" ,choices=status_choices , default=1) #default 当他没有选的时候 默认选1


class Task(models.Model):
    '''任务表单'''
    level_choices = (
        (1,"紧急"),
        (2,"重要"),
        (3,"无关"),
    )

    level = models.SmallIntegerField(verbose_name="级别" ,choices=level_choices , default=1)

    title =  models.CharField(verbose_name="标题" , max_length=64)
    detail = models.TextField(verbose_name="详细信息")

    user = models.ForeignKey(verbose_name="负责人" , to="Admin" , on_delete=models.CASCADE)


class Order(models.Model):
    ''' 订单表单 '''
    oid = models.CharField(verbose_name="订单号" , max_length=64)
    title = models.CharField(verbose_name="商品名称" , max_length=32)
    price = models.IntegerField(verbose_name="价格")

    status_choices = (
        (1,"待支付"),
        (2,"已支付"),
    )

    status = models.SmallIntegerField(verbose_name="状态" , choices=status_choices, default=1)

    admin = models.ForeignKey(verbose_name="管理员" , to="Admin" , on_delete=models.CASCADE)



class Boss(models.Model):
    ''' 老板（文件上传） '''
    name = models.CharField(verbose_name="姓名",max_length=32)
    age = models.IntegerField(verbose_name="年龄")
    img = models.CharField(verbose_name="头像",max_length=128)


class City(models.Model):
    """ 城市 """
    name = models.CharField(verbose_name="名称", max_length=32)
    count = models.IntegerField(verbose_name="人口")

    # 本质上数据库也是CharField，自动保存数据。
    img = models.FileField(verbose_name="Logo", max_length=128, upload_to='city/')


app01/views/account.py

from django.shortcuts import render,redirect,HttpResponse
from django import forms
from io import BytesIO

from app01 import models
from app01.utils.bootstrap import BootStrapForm,BootStrapModelForm
from app01.utils.encrypt import md5
from app01.utils.code import check_code

class LoginFrom(BootStrapForm):
    username = forms.CharField(
        label="用户名",
        widget=forms.TextInput,
        required=True #必须填写 不能为空
    )
    password = forms.CharField(
        label="密码",
        #widget=forms.PasswordInput, 
        widget=forms.PasswordInput(render_value=True), #render_value=True让这个字段在前端保留用户输入的数据
        required=True #必须填写 不能为空
    )
    code = forms.CharField(
        label="验证码",
        widget=forms.TextInput,
        required=True #必须填写 不能为空
    )

    def clean_password(self):
        pwd = self.cleaned_data.get('password')
        return md5(pwd)


def login(request):
    ''' 账号登录 '''
    if request.method == "GET":
        form = LoginFrom()  
        return render(request,"login.html",{"form":form})

    form = LoginFrom(data = request.POST)
    if form.is_valid():
        # print('cleaned_data',form.cleaned_data)


        #验证码的校验
        user_code_input = form.cleaned_data.pop('code')  #pop()当取出后在进行删除 我们数据库没有存储code字段 下面的数据库就查找不到
        code = request.session.get('image_code',"")
        if code.upper() != user_code_input.upper():
            form.add_error("code","验证码错误")
            return render(request,"login.html",{"form":form})


        admin_object = models.Admin.objects.filter(**form.cleaned_data).first()
        print('admin_object',admin_object)
        if not admin_object:
            form.add_error("password","用户名或者密码错误")
            return render(request,"login.html",{"form":form})
            
        # 用户名和密码正确
        # 网站生成随机字符串; 写到用户浏览器的cookie中；在写入到session中；
        request.session["info"] = { 'id':admin_object.id,'name':admin_object.username }
        #session 只能保存1天
        request.session.set_expiry(60 * 60 * 24 * 1)
        return redirect("/admin/list/")
    
    return render(request,"login.html",{"form":form})
    


def image_code(reuqest):
    ''' 验证码的生成 '''

    # 调用pillow函数，生成图片
    img,code_string = check_code()

    reuqest.session['image_code'] = code_string
    #验证码只有60秒有效
    reuqest.session.set_expiry(60)

    stream = BytesIO()
    img.save(stream , 'png')

    return HttpResponse(stream.getvalue())


def logout(request):
    ''' 账号退出 '''
    request.session.clear()
    return redirect('/login/')


app01/views/admin.py
from typing import Any, Dict
from django.shortcuts import render,redirect
from django import forms
from django.core.exceptions import ValidationError

from app01 import models
from app01.utils.pagination import Pagination
from app01.utils.bootstrap import BootStrapModelForm
from app01.utils.encrypt import md5




def admin_list(request):
    '''管理员列表'''

    # info_dict = request.session["info"]
    # print(info_dict["id"])
    # print(info_dict["name"])

    data_dict = {} #创建一个字典
    search_data = request.GET.get('q','') #获取get请求 查看q是否传值 有的话赋值
    if search_data: #判断是否获取到值
        data_dict["username__contains"] = search_data # 这里是存入数组 
        #在数据库中“username__contains”是选出包含search_data字段的所有数据
    
    queryset = models.Admin.objects.filter(**data_dict) #在数据库中找出所匹配的数据
    page_object = Pagination(request,queryset) #Pagination 一个自己写的分页 进行引入

    context = {
        "search_data":search_data,
        "queryset":page_object.page_queryset,
        "page_string" : page_object.html(),
        "error" : page_object.error,
    }

    return render(request,"admin_list.html",context)



class  AdminModelForm(BootStrapModelForm):
    confirm_password = forms.CharField(
        label="确认密码",
        widget=forms.PasswordInput(render_value= True) #(render_value= True) 保留之前所写的 密码不会消失
    )

    class Meta:
        model = models.Admin
        fields = ['username','password','confirm_password']
        widgets = {
            "password":forms.PasswordInput(render_value=True) #(render_value= True) 保留之前所写的 密码不会消失
        }

    def clean_password(self):
        pwd = self.cleaned_data.get("password")

        return md5(pwd)

    def clean_confirm_password(self):
        
        pwd = self.cleaned_data.get("password")
        confirm = md5(self.cleaned_data.get("confirm_password"))
        if confirm != pwd :
            raise ValidationError("确认密码输入不一致")
        
        # return返回什么 数据库就存储什么
        return confirm
         

class AdminEditModelForm(BootStrapModelForm):
    class Meta:
        model = models.Admin
        fields = ['username']


def admin_add(request):
    '''管理员添加'''

    title = "添加管理员"

    if request.method == 'GET':
        form = AdminModelForm()
        return render(request , "public_add.html",{"title":title,"form":form})
    
    form = AdminModelForm(data = request.POST)

    if form.is_valid():
        # print(form.cleaned_data)
        form.save()
        return redirect("/admin/list/")

    return render(request , "public_add.html" ,{"title":title,"form":form})



def admin_edit(request,nid):
    ''' 管理员编辑 '''
    title  = '编辑管理员页面'
    row_object = models.Admin.objects.filter(id = nid).first()
    if not row_object: #判断数据是否存在
        return redirect("/admin/list")
        # return render(request,"error.html")

    if request.method == "GET":
        form = AdminEditModelForm(instance = row_object)
        # form = AdminEditModelForm() # instance = row_object加上就能显示之前数据 

        return render(request,"public_add.html" ,{"title":title,"form":form})

    form = AdminEditModelForm(data = request.POST,instance = row_object)
    if form.is_valid():

        form.save()
        return redirect("/admin/list/")
    
    return render(request,"public_add.html" ,{"title":title,"form":form})



def admin_delete(request,nid):
    ''' 删除管理员 '''

    models.Admin.objects.filter(id = nid).delete()
    return redirect("/admin/list/")



class AdminResetModelForm(BootStrapModelForm):
    confirm_password = forms.CharField(
        label="确认密码",
        widget=forms.PasswordInput(render_value= True) #(render_value= True) 保留之前所写的 密码不会消失
    )

    class Meta:
        model = models.Admin
        fields = ['password','confirm_password']
        widgets = {
            "password":forms.PasswordInput(render_value=True) #(render_value= True) 保留之前所写的 密码不会消失
        }

    def clean_password(self):
        pwd = self.cleaned_data.get("password")
        md5_pwd = md5(pwd)
        
        #去数据库进行对比（功能不能让其输入的密码跟原密码一样）
        exists = models.Admin.objects.filter(id = self.instance.pk,password = md5_pwd).exists()
        if exists:
            raise ValidationError("新密码与原密码一致")
        return md5_pwd

    def clean_confirm_password(self):
        
        pwd = self.cleaned_data.get("password")
        confirm = md5(self.cleaned_data.get("confirm_password"))
        if confirm != pwd :
            raise ValidationError("确认密码输入不一致")
        
        # return返回什么 数据库就存储什么
        return confirm

def admin_reset(request,nid):
    ''' 管理员密码重置 '''
    title = '管理员密码重置'
    row_object = models.Admin.objects.filter(id = nid).first()
    if not row_object:
        return redirect("/admin/list/")

    if request.method == "GET":
        form = AdminResetModelForm()
        return render(request , "public_add.html",{"title":title,"form":form})
    
    form = AdminResetModelForm(request.POST,instance = row_object)

    if form.is_valid():
        form.save()

        return redirect("/admin/list/")
    
    return render(request , "public_add.html",{"title":title,"form":form})


app01/views/chart.py
"""
这里面的数据都可以去数据库拿去

1.首先创建一个数据库
2.跟自己的需求进行填写
3.将数据导入出来


"""

from django.shortcuts import render,HttpResponse
from django.http import JsonResponse


def chart_list(request):
    ''' 图表展示 '''

    return render(request,"chart_list.html")


def chart_line(request):
    ''' 折线图数据 '''
    
    legend = ['农夫山泉',"怡宝"]
    x_axis = ['1月', '2月', '3月', '4月', '5月', '6月','7月','8月','9月','10月','11月','12月']
    series_list = [
                {
                    "name": '农夫山泉',
                    "type": 'line',
                    "data": [150, 300, 80, 418, 135, 350, 260, 500, 450, 350, 120, 255],
                },
                {
                    "name": '怡宝',
                    "type": 'line',
                    "data": [15, 200, 280, 118, 335, 50, 160, 100, 250, 150, 320, 80]
                }
                ]
    
    data_list = {
        "status":True,
        "data":{
            'legend':legend,
            'x_axis':x_axis,
            'series_list':series_list,
        }
    }

    return JsonResponse(data_list)



def chart_bar(request):
    ''' 柱状图数据 '''
    
    legend = ['小花',"小明"]
    x_axis = ['1月', '2月', '3月', '4月', '5月', '6月']
    series_list = [
                {
                    "name": '小花',
                    "type": 'bar',
                    "data": [5, 20, 36, 10, 10, 20],
                },
                {
                    "name": '小明',
                    "type": 'bar',
                    "data": [15, 30, 5, 40, 60, 100]
                }
                ]
    
    data_list = {
        "status":True,
        "data":{
            'legend':legend,
            'x_axis':x_axis,
            'series_list':series_list,
        }
    }

    return JsonResponse(data_list)

def chart_pie(request):
    ''' 饼图数据 '''
    
    # legend = ['小花',"小明"]
    # x_axis = ['1月', '2月', '3月', '4月', '5月', '6月']
    series_list = [
                    { 'value': 1048, 'name': '抖音' },
                    { 'value': 735, 'name': '微博' },
                    { 'value': 580, 'name': 'QQ' },
                    { 'value': 484, 'name': '小红书' },
                    { 'value': 300, 'name': '微信' }
                ]
    
    data_list = {
        "status":True,
        "data":{
            # 'legend':legend,
            # 'x_axis':x_axis,/
            'series_list':series_list,
        }
    }

    return JsonResponse(data_list)

app01/views/city.py

from django.shortcuts import render,redirect,HttpResponse

from app01 import models
from app01.utils.bootstrap import BootStrapModelForm


def city_list(request):
    ''' 城市展示 '''
    queryset = models.City.objects.all()
    return render(request,"city_list.html",{"queryset":queryset})


class UpModelFormCity(BootStrapModelForm):
    bootstrap_exclude_fields = ['img']
    class Meta:
        model = models.City
        fields = '__all__'
def city_add(request):
    ''' 城市添加 '''
    
    title = '城市添加'
    if request.method == 'GET':
        form = UpModelFormCity()
        return render(request,'city_add.html',{'form':form,'title':title})
    
    form = UpModelFormCity(data=request.POST,files=request.FILES)
    if form.is_valid():
        form.save()
        return redirect('/city/list/')

    return render(request,'city_add.html',{'form':form,'title':title})

app01/templates/city_add.html
{% extends 'layout.html' %}

{% block content %}
<div class="container">
    <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">{{ title }}</h3>
    </div>
    <div class="panel-body">
        <form method="post" enctype="multipart/form-data" novalidate>
            {% csrf_token %} 
            
            {% for field in form %}
            <div class="form-group">  
                <label>{{ field.label }}</label>
                    {{ field }}
                <span style="color: red;"> {{ field.errors.0 }}</span>       
            </div>
            {% endfor %}  

            <button type="submit" class="btn btn-primary">保 存</button>
        </form>
    </div>
  </div>
</div>
{% endblock %}

app01/templates/error.html
{% extends 'layout.html' %}

{% block content %}

<div class="container">

    <div class="alert alert-danger" role="alert">没有该数据</div>
</div>



{% endblock %}

app01/templates/order_list.html
{% extends 'layout.html' %}

{% block content %}
<div class="container">
    <div>
        <input type="button" value="新建订单1" class="btn btn-success" data-toggle="modal" data-target="#myModal" >
        <input  id="btnAdd" type="button" value="新建订单2" class="btn btn-success" >
    </div>

    <div class="panel panel-default" style="margin-top: 10px;">
                
        <div class="panel-heading">
            <span class="glyphicon glyphicon-list" aria-hidden="true"></span>
            订单
        </div>
  
        <!-- Table -->
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>ID</th>
              <th>订单号</th>
              <th>商品名称</th>
              <th>价格</th>
              <th>状态</th>
              <th>管理员</th>
              <th>操作</th>
            </tr>
          </thead>
          <tbody>
            {% for obj in queryset %}
            <tr uid="{{ obj.id }}">
              <th scope="row">{{ obj.id }}</th>
              <td>{{ obj.oid }}</td>
              <td>{{ obj.title }}</td>
              <td>{{ obj.price }}</td>
              <td>{{ obj.get_status_display }}</td>
              <td>{{ obj.admin.username }}</td>
              <td>
                <input uid="{{ obj.id }}" type="button" class="btn btn-primary btn-xs btn-edit" value="编辑">
                <input uid="{{ obj.id }}" class="btn btn-danger btn-xs btn-delete" type="button" value="删除">
            </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>

      <ul class="pagination">
        {{ page_string }}
      </ul>
      <span><a style="color: red;">{{ error }}</a></span>

        <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">订单填写</h4>
        </div>
        <div class="modal-body">
            <form id="addForm" novalidate>
                <div class="clearfix" >
                    {% for field in form %}
                        <div class="col-xs-6" >
                            <div class="form-group" style="position: relative;margin-bottom: 20px;" > 
                                <label>{{ field.label }}</label>
                                    {{ field }}   
                                    <span class="error-msg" style="color: red; position: absolute;"></span> 
                            </div>
                        </div>
                    {% endfor %}  
                </div>
            </form>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">取 消</button>
            <button  id="btnSave" type="button" class="btn btn-primary">保 存</button>
        </div>
        </div>
    </div>
    </div>

    <!-- 删除（对话框） -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">

            <div class="alert alert-danger alert-dismissible fade in" role="alert">
                <h4>是否确定删除？</h4>
                <p style="margin: 10px 0;"> 删除后，所有关联的相关数据都会被删除!</p>
                <p style="text-align: right;">
                    <button id="btnConfirmDelete" type="button" class="btn btn-danger">确 定</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">取 消</button>
                </p>
            </div>

        </div>
    </div>

</div>

{% endblock %}

{% block js %}

    <script type="text/javascript">
        var DELETE_ID;
        var EDIT_ID;

        $(function () {
            bindBtnAddEvent();
            bindBtnSaveEvent();
            bindBtnDeleteEvent();
            bindBtnConfirmDeleteEvent();
            bindBtnEditEvent();
        })

        function bindBtnAddEvent() {
            $("#btnAdd").click(function () {

                EDIT_ID = undefined;
                // 清空弹出框里面的内容
                $("#addForm")[0].reset();
                
                //编辑输入框的标题
                $("#myModalLabel").text("添加新订单");


                //点击显示对话框
                $('#myModal').modal('show');
                
            })
            
        }

        function bindBtnEditEvent() {
            $(".btn-edit").click(function () {
                // 清空弹出框里面的内容
                $("#addForm")[0].reset();

                // 点击后获取 id值
                var uid = $(this).attr("uid");
                EDIT_ID = uid;

                //编辑输入框的标题
                $("#myModalLabel").text("订单编辑");

                // 展示弹出框
                $('#myModal').modal('show');

                // 向后台发送ajax请求 获取数据
                $.ajax({
                    url:"/order/detail/",
                    type : "get",
                    data : {
                        uid : uid,
                    },
                    dataType : "JSON",
                    success:function (res) {
                        if (res.status) {
                            $.each(res.data,function (name,value) {
                                $("#id_"+name).val(value);
                            })
                        }else{
                            alert(res.error);
                        }
                    }
                })


            });
            
        }
        
        function bindBtnDeleteEvent() {
            $(".btn-delete").click(function () {
                 //点击显示对话框
                $('#deleteModal').modal('show');

                //获取当前行的ID并赋值给全局变量
                DELETE_ID = $(this).attr("uid");
            })
           
        }

        function bindBtnConfirmDeleteEvent() {
            $("#btnConfirmDelete").click(function () {
                $.ajax({
                    url:"/order/delete/",
                    type:"GET",
                    data:{
                        uid:DELETE_ID,
                    },
                    dataType:"JSON",
                    success:function (res){
                        if (res.status) {
                            //隐藏删除框
                            //$("#deleteModal").modal('hide');
                            //在页面上删除当前一行数据（js格式删除）
                            //$("tr[uid="+ DELETE_ID +"]").remove();
                            //将其数据制空
                            //DELETE_ID = 0;
                            
                            //简单思路 可以直接刷新
                            location.reload();    

                        }else{
                            alert(res.error);

                        }
                    }
                })
            });
            
        }

        function bindBtnSaveEvent() {
            $("#btnSave").click(function () {
                //在点击之前清空 span的框的值
                $(".error-msg").empty();
                if (EDIT_ID) {
                    // 编辑
                    doEdit();
                }else{
                    // 添加
                    doAdd();
                }
            })
            
        }

        function doAdd() {
            $.ajax({
                    url:"/order/add/",
                    type:'post',
                    data : $("#addForm").serialize(),
                    dataType:'JSON',
                    success:function (res) {
                        if (res.status) {
                            //alert("创建成功");
                            
                            //清空表单  $("#addForm")是JQuery对象  $("#addForm")[0] 是DOM对象
                            $("#addForm")[0].reset();

                            //关闭对话框
                            $('#myModal').modal('hide');
                            location.reload();

                        }else{
                            $.each(res.error,function (name,errorList) {
                                $("#id_"+name).next().text(errorList[0]);
                            })
                        }
                        
                    }

                })
         
        }

        function doEdit() {
            $.ajax({
                    url:"/order/edit/"+"?uid="+EDIT_ID,
                    type:'post',
                    data : $("#addForm").serialize(),
                    dataType:'JSON',
                    success:function (res) {
                        if (res.status) {
                            //alert("创建成功");
                            
                            //清空表单  $("#addForm")是JQuery对象  $("#addForm")[0] 是DOM对象
                            $("#addForm")[0].reset();

                            //关闭对话框
                            $('#myModal').modal('hide');
                            location.reload();

                        }else{
                            if (res.tips) {
                                alert(res.tips);
                            }else{
                                $.each(res.error,function (name,errorList) {
                                    $("#id_"+name).next().text(errorList[0]);
                                })
                            }
                        }
                        
                    }

                })

        }


    </script>

{% endblock %}


app01/templates/task_list.html
{% extends 'layout.html' %}

{% block content %}
<div class="container">

    <div class="panel panel-default">
        <div class="panel-heading">任务表单</div>
        <div class="panel-body">
            <div class="panel-body">
                <form id="addForm" novalidate>
                    <div class="clearfix" >
                        {% for field in form %}
                            <div class="col-xs-6" >
                                <div class="form-group" style="position: relative;margin-bottom: 20px;" > 
                                    <!-- position: relative; 相对定位    -->
                                    <label>{{ field.label }}</label>
                                        {{ field }}   
                                        <span class="error-msg" style="color: red; position: absolute;"></span> 
                                        <!-- position: absolute; 绝对定位 -->
                                </div>
                            </div>
                        {% endfor %}  
                    </div>
                    <button type="button" id="btnAdd" class="btn btn-primary">保 存</button>
                </form>
            </div>
        </div>
      </div>

      <div class="panel panel-default">     
        <div class="panel-heading">
            <span class="glyphicon glyphicon-list" aria-hidden="true"></span>
            任务表单
        </div>
  
        <!-- Table -->
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>ID</th>
              <th>标题</th>
              <th>级别</th>
              <th>详细信息</th>
              <th>负责人</th>
              <th>操作</th>
            </tr>
          </thead>
          <tbody>
            {%for obj in queryset %}
            <tr>
              <th scope="row">{{ obj.id }}</th>
              <td>{{ obj.title }}</td>
              <td>{{ obj.get_level_display }}</td>
              <td>{{ obj.detail }}</td>
              <td>{{ obj.user.username }}</td>
              <td>
                <a class="btn btn-primary btn-xs" href="#" >编辑</a> 
                <a class="btn btn-danger btn-xs" href="#">删除</a>
            </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    <ul class="pagination">
        {{ page_string }}
    </ul>
    <span><a style="color: red;">{{ error }}</a></span>

</div>

{% endblock %}


{% block js %}
    <script type="text/javascript">

        $(function () {
            // 
            BtnAddEvent();
        })

        function BtnAddEvent() {
            $("#btnAdd").click(function () {
                //在点击之前清空 span的框的值
                $(".error-msg").empty();

                $.ajax({
                url:'/task/add/',
                type:"post", 
                data:$("#addForm").serialize(),
                dataType:"JSON",
                success:function(res){
                    if (res.status) {
                        alert("添加成功");
                        location.reload();
                    }else{
                            //console.log(res.error);
                        //循环
                        $.each(res.error,function (name,data) {
                            //console.log(name , data);
                            $("#id_" + name).next().text(data[0]);
                        })
                    }
                }
            })
            }

            ) 
        }

   </script>
{% endblock %}